FROM telegraf:latest

RUN mkdir /build
WORKDIR  /build

COPY processors/forecasting.py ./
COPY processors/forecasting2.py ./
COPY requirements.txt ./

RUN apt update -y && apt install -y python python-pip python3 python3-pip 

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

WORKDIR /


ENTRYPOINT ["/entrypoint.sh"]
CMD ["telegraf"]